routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth::routes();
Auth::routes(['verify' => true]);
Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');

Route::get('/readnotification/{id}', 'OrderController@readnotification')->name('readnotification');

    Route::get('/home', 'HomeController@index')->name('Home');

    Route::group(['middleware' => ['isAdmin', 'auth']], function() {

        Route::get('users/allUsers', 'UserController@index')->name('users.allusers');
        Route::resource('users', 'UserController');


        Route::get('roles/allRoles', 'RoleController@index')->name('roles.allroles');
        Route::resource('roles', 'RoleController');


        Route::get('permissions/allPermissions', 'PermissionController@index')->name('permissions.allpermissions');
        Route::resource('permissions', 'PermissionController');


        Route::get('keywords/allKeywords', 'KeywordController@index')->name('keywords.allkeywords');
        Route::resource('keywords', 'KeywordController');


        Route::get('industry/allIndustries', 'IndustryController@index')->name('industry.allindustries');
        Route::resource('industry', 'IndustryController');

    });

    Route::group(['prefix' => 'blogs', 'as' => 'blogs','middleware'=>'auth'],function (){

        Route::get('/','BlogController@index')->name('.index')->middleware('payment');

        Route::get('/allBlogs','BlogController@index')->name('.allblogs')->middleware('payment');
        Route::get('/list','BlogController@show')->name('.bloglist');
        Route::post('/searchresult', 'BlogController@blog_search')->name('.searchresult');
        Route::post('/store', 'BlogController@store')->name('.store');
        Route::get('/{id}/edit', 'BlogController@edit')->name('.edit');
        Route::get('/create','BlogController@create')->name('.create');
        Route::get('/{id}/delete', 'BlogController@destroy')->name('.destroy');
        Route::post('/{id}/update', 'BlogController@update')->name('.update');
        Route::post('/add_to_cart','BlogController@add_to_cart')->name('.add_to_cart');
        Route::post('/add_to_cart_update','BlogController@add_to_cart_update')->name('.add_to_cart_update');
        Route::get('/viewDetails/{id}', 'BlogController@viewDetails')->name('.viewDetails');
     });

   // Route::resource('blogs', 'BlogController')->middleware('isAdmin');
    // Route::get('/blogs', 'BlogController@index')->name('blogs.index')->middleware('auth','payment');
    // Route::get('/blogs/list', 'BlogController@show')->name('blogs.bloglist')->middleware('isAdmin');
    // Route::post('/blogs/searchresult','BlogController@blog_search')->name('blogs.searchresult')->middleware('auth');;
    // Route::post('/blogs/add_to_cart','BlogController@add_to_cart')->name('blogs.add_to_cart');
    // Route::post('/blogs/add_to_cart_update','BlogController@add_to_cart_update')->name('blogs.add_to_cart_update');


    Route::get('/cart','BlogController@cart')->name('blog.cart')->middleware('auth');
    Route::post('/cart_update','BlogController@cart_update')->name('blog.cart_update');
    Route::post('/cart_delete','BlogController@cart_delete')->name('blog.cart_delete');
    Route::get('/checkout','BlogController@checkout')->name('blog.checkout')->middleware('auth');

    Route::resource('orders', 'OrderController')->middleware('auth');
    //Route::post('/orders/update/{id}', 'OrderController@update')->name('orders.update');
    Route::get('paywithpaypal', array('as' => 'addmoney.paywithpaypal','uses' => 'AddMoneyController@payWithPaypal',));
    Route::post('paypal', array('as' => 'addmoney.paypal','uses' => 'AddMoneyController@postPaymentWithpaypal',));
    Route::get('paypal', array('as' => 'payment.status','uses' => 'AddMoneyController@getPaymentStatus',));
    Route::get('/orders/create', array('as' => 'orders.status','uses' => 'OrderController@getOrderStatus',));

resources/views/layouts/backend/alert.blade.php
@if(Session::has('flash_message'))

    <section class="content-header">
        <div class="row">
            <div class="col-md-12">

                <div class="custom-alerts alert alert-success"><em> {!! session('flash_message') !!}</em>
                </div>

            </div>
        </div>
    </section>

@endif

@if(Session::has('flash_error_message'))

    <section class="content-header">
        <div class="row">
            <div class="col-md-12">
                <div class="custom-alerts alert alert-danger"><em> {!! session('flash_error_message') !!}</em>
                </div>
            </div>
        </div>
    </section>


@endif

@if ($message = Session::get('success'))

    <section class="content-header">
        <div class="row">
            <div class="col-md-12">

                <div class="custom-alerts alert alert-success" style=" z-index: 100000 !important;">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                    {!! $message !!}
                </div>
                <?php Session::forget('success');?>

            </div>
        </div>
    </section>

@endif

@if ($message = Session::get('error'))

    <section class="content-header">
        <div class="row">
            <div class="col-md-12">

                <div class="custom-alerts alert alert-danger" style=" z-index: 100000 !important;">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                    {!! $message !!}
                </div>
                <?php Session::forget('error');?>

            </div>
        </div>
    </section>

@endif

resources/views/layouts/backend/app.blade.php
<!DOCTYPE html>
<html>
@include('layouts.backend.head')
<body class="skin-blue sidebar-mini fixed">


@include('layouts.backend.header')

{{--@if(Session::has('flash_message'))--}}
{{--    <div class="container">--}}
{{--        <div class="row">--}}
{{--            <div class="col-md-6 col-md-push-3">--}}
{{--                <div class="custom-alerts alert alert-success"><em> {!! session('flash_message') !!}</em>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}
{{--@endif--}}

{{--@if(Session::has('flash_error_message'))--}}
{{--    <div class="container">--}}
{{--        <div class="row">--}}
{{--            <div class="col-md-6 col-md-push-3">--}}
{{--                <div class="custom-alerts alert alert-danger"><em> {!! session('flash_error_message') !!}</em>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}
{{--@endif--}}

{{--@if ($message = Session::get('success'))--}}
{{--    <div class="container">--}}
{{--        <div class="row">--}}
{{--            <div class="col-md-6 col-md-push-3">--}}
{{--                <div class="custom-alerts alert alert-success" style=" z-index: 100000 !important;">--}}
{{--                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>--}}
{{--                    {!! $message !!}--}}
{{--                </div>--}}
{{--                <?php Session::forget('success');?>--}}

{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}
{{--@endif--}}

{{--@if ($message = Session::get('error'))--}}
{{--    <div class="container">--}}
{{--        <div class="row">--}}
{{--            <div class="col-md-6 col-md-push-3">--}}
{{--                <div class="custom-alerts alert alert-danger" style=" z-index: 100000 !important;">--}}
{{--                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>--}}
{{--                    {!! $message !!}--}}
{{--                </div>--}}
{{--                <?php Session::forget('error');?>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}
{{--@endif--}}

{{--@if (count($errors) > 0)--}}
{{--    <div class="container">--}}
{{--        <div class="row">--}}
{{--            <div class="col-md-6 col-md-push-3">--}}
{{--                <div class="custom-alerts alert alert-danger">--}}
{{--                    <ul>--}}
{{--                        @foreach ($errors->all() as $error)--}}
{{--                            <li>{{ $error }}</li>--}}
{{--                        @endforeach--}}
{{--                    </ul>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}
{{--@endif--}}



@include('layouts.backend.nav')

@yield('section')


@include('layouts.backend.script')
@yield('script')
</body>
</html>

resources/views/layouts/backend/head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{asset('backend/css/bootstrap.min.css')}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('backend/css/font-awesome/css/font-awesome.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{asset('backend/css/ionicons.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('backend/css/AdminLTE.min.css')}}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{asset('backend/css/_all-skins.min.css') }}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{{asset('backend/css/morris.css') }}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{ asset('backend/css/jquery-jvectormap.css')}}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{asset('backend/css/bootstrap-datepicker.min.css') }}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{ asset('backend/css/daterangepicker.css') }}">
    <link rel="stylesheet" href="{{ asset('backend/iCheck/all.css') }}">
    <link rel="stylesheet" href="{{ asset('backend/css/select2.min.css') }}">

    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{asset('backend/css/bootstrap3-wysihtml5.min.css') }}">

    <link rel="stylesheet" href="{{asset('backend/css//dataTables.bootstrap.min.css') }}">

    <link rel="stylesheet" href="{{ asset('backend/css/custom.css') }}">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

resources/views/layouts/backend/header.blade.php
<style>
    .fa.fa-shopping-cart {
        position: absolute;
        right: 0px;
        top: 0px;
        padding: 9px 12px 7px 10px;
        background: red;
        height: 100%;
        font-size: 130%;
    }

    .add-to-cart {
        transition: 0.4s;
        color: #fff;
        background-color: #303030;
        text-transform: uppercase;
        position: relative;
        padding-right: 52px
    }
</style>




<header class="main-header">

    <!-- Logo -->
    <a href="{{route('Home')}}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>G</b>P-P</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Guest Posting</b> Portal</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

                @hasrole('admin')

                <?php
                    $rr = \app\User::find(1);
                 ?>

                <li class="dropdown messages-menu open dropdown-notifications">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                      {{-- <i class="fa fa-envelope-o"></i> --}}
                    <span class="label label-success notif-count">{{$rr->unreadnotifications->count()}}</span>

                      <i data-count="0" class="glyphicon glyphicon-bell notification-icon"></i>
                    </a>
                    <ul class="dropdown-menu">
                      <li class="header">You have {{$rr->unreadnotifications->count()}} new messages</li>


                      <li>
                        <!-- inner menu: contains the actual data -->
                        <ul class="menu">
                        <?php
                            foreach( $rr->unreadnotifications as $p){
                                ?>
                          <li>
                          <a href="{{route('readnotification',$p->id)}}">
                              <div class="pull-left">
                                <img src="" class="img-circle" alt="Image">
                              </div>
                              <h4>
                                {{-- Order --}}
                                <small><i class="fa fa-clock-o"></i> 2 days</small>
                              </h4>
                              <?php $un = unserialize($p->data['data']['user_meta']); ?>
                              <b>{{$un['fname']}} order a blog</b>

                            </a>
                          </li>

                      <?php } ?>
                    </ul>
                </li>
                      <li class="footer"><a href="#">See All Messages</a></li>
                    </ul>
                  </li>


                @else
                    <li style="margin-top:10px">
                        {{--    <form method="post" enctype="multipart/form-data" action="{{route('blog.cart')}}" >--}}
                        {{--    {{ csrf_field() }}--}}
                        {{--    <input type="hidden" name="url" class="on-load-url" value="{{url('/blogs/add_to_cart_update')}}"/>--}}
                        {{--    <a href="{{route('blog.cart')}}"  class="add-to-cart" >--}}
                        {{--        <i class="fa fa-shopping-cart" aria-hidden="true"></i> <span class="cart-detail"> </span> item(s)--}}
                        {{--    </a>--}}
                        <input type="hidden" name="url" class="on-load-url"
                               value="{{url('/blogs/add_to_cart_update')}}"/>
                        <a href="{{route('blog.cart')}}" class="btn btn-app bg-navy custom-cart-btn">
                            <span class="badge bg-red cart-detail"> </span>
                            <i class="fa fa-inbox"> <span class="custom-cart"> Cart </span></i>
                        </a>
                        {{-- </form> --}}
                    </li>
                    @endrole

                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{{asset('backend/img/user2-160x160.jpg') }}" class="user-image" alt="User Image">
                            <span class="hidden-xs">{{strtoupper(Auth::user()->name) }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="{{asset('backend/img/user2-160x160.jpg') }}" class="img-circle"
                                     alt="User Image">
                                <p class="custom-user-header">
                                    {{ ucfirst(Auth::user()->name)  }}
                                    <small>Member
                                        since {{ \Carbon\Carbon::parse(Auth::user()->created_at)->format(' F. Y') }}</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-right">
                                    <a class="btn bg-navy btn-flat" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    @if (\Request::is('Home'))
                                        working
                                    @endif

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                          style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </div>
                            </li>
                            <!-- Menu Footer End -->
                        </ul>
                    </li>


            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/backend/nav.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{asset('backend/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{strtoupper(Auth::user()->name) }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        {{--            <form action="#" method="get" class="sidebar-form">--}}
        {{--                <div class="input-group">--}}
        {{--                    <input type="text" name="q" class="form-control" placeholder="Search...">--}}
        {{--                    <span class="input-group-btn">--}}
        {{--                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>--}}
        {{--                    </button>--}}
        {{--                  </span>--}}
        {{--                </div>--}}
        {{--            </form>--}}
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->


        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>

            <li class="@if(\Request::is('home')) active menu-open @endif">
                <a href="{{ route('Home')}}">
                    <i class="fa fa-home"></i> <span>Dashboard</span>
                </a>
            </li>

            @hasrole('admin')

            <li class="treeview @if(\Request::is('users/*')) active menu-open @endif">
                <a href="#">
                    <i class="fa fa-user"></i> <span>User</span>
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@if(\Request::is('users/allUsers')) active @endif"><a href="{{route('users.allusers')}}"><i class="fa fa-circle-o"></i> All User</a>
                    </li>
                    <li class="@if(\Request::is('users/create')) active @endif"><a href="{{route('users.create')}}"><i class="fa fa-circle-o"></i> Add User</a></li>
                </ul>
            </li>

            <li class="treeview @if(\Request::is('roles/*')) active menu-open @endif">
                <a href="#">
                    <i class="fa fa-users"></i> <span>Roles</span>
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@if(\Request::is('roles/allRoles')) active @endif"><a href="{{ route('roles.allroles')}}"><i class="fa fa-circle-o"></i> All Roles</a></li>
                    <li class="@if(\Request::is('roles/create')) active @endif"><a href="{{url('roles/create')}}" ><i class="fa fa-circle-o"></i> Add Role</a></li>
                </ul>
            </li>
            <li class="treeview @if(\Request::is('permissions/*')) active menu-open @endif">
                <a href="#">
                    <i class="fa fa-key"></i> <span>Permissions</span>
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@if(\Request::is('permissions/allPermissions')) active @endif"><a href="{{route('permissions.allpermissions')}}"><i class="fa fa-circle-o"></i> All Permissions</a>
                    </li>
                    <li class="@if(\Request::is('permissions/create')) active @endif"><a href="{{route('permissions.create')}}"><i class="fa fa-circle-o"></i>Add Permission</a></li>

                </ul>
            </li>
            <li class="treeview @if(\Request::is('keywords/*')) active menu-open @endif">
                <a href="#">
                    <i class="fa fa-font"></i><span>Keywords</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@if(\Request::is('keywords/allKeywords')) active @endif"><a href="{{route('keywords.allkeywords')}}"><i class="fa fa-circle-o"></i> All Keywords</a>
                    </li>
                    <li class="@if(\Request::is('keywords/create')) active @endif"><a href="{{route('keywords.create')}}"><i class="fa fa-circle-o"></i> Add keyword</a></li>
                </ul>
            </li>

            <li class="treeview @if(\Request::is('industry/*')) active menu-open @endif">
                <a href="#">
                    <i class="fa fa-industry"></i><span>Industries</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li class="@if(\Request::is('industry/allIndustries')) active @endif"><a href="{{route('industry.allindustries')}}"><i class="fa fa-circle-o"></i> All Industries</a>
                    </li>
                    <li class="@if(\Request::is('industry/create')) active @endif"><a href="{{route('industry.create')}}"><i class="fa fa-circle-o"></i> Add Industry</a></li>
                </ul>
            </li>
            @endrole
            <li class="treeview @if(\Request::is('blogs/*')) active menu-open @endif ">

                <a href="#">
                    <i class="fa fa-sticky-note-o"></i><span>Blogs</span>
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    @hasrole('admin')
                    <li class="@if(\Request::is('blogs/create')) active @endif"><a href="{{route('blogs.create')}}"><i class="fa fa-circle-o"></i> Add Blog</a></li>
                    <li class="@if(\Request::is('blogs/list')) active @endif"><a href="{{route('blogs.bloglist')}}"><i class="fa fa-circle-o"></i> Blog List</a></li>
                    @else
                        <li class="@if(\Request::is('blogs/allBlogs')) active @endif"><a href="{{route('blogs.allblogs')}}"><i class="fa fa-circle-o"></i> All Blogs</a>
                        </li>
                    @endrole
                </ul>

            </li>
            <li class="treeview @if(\Request::is('orders')) active menu-open @endif">
                <a href="#">
                    <i class="ion ion-bag"></i><span>Orders</span>
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    @hasrole('admin')
                        <li class="@if(\Request::is('orders')) active @endif"><a href="{{route('orders.index')}}"><i class="fa fa-circle-o"></i> All Orders</a></li>
                    @else
                        <li class="@if(\Request::is('orders')) active @endif"><a href="{{route('orders.index')}}"><i class="fa fa-circle-o"></i> My Orders</a>
                        </li>
                    @endrole
                </ul>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/layouts/backend/script.blade.php
<script src="{{asset('backend/js/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('backend/js/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('backend/js/bootstrap.min.js') }}"></script>
<!-- Morris.js charts -->
<script src="{{asset('backend/js/raphael.min.js') }}"></script>
<script src="{{asset('backend/js/morris.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{asset('backend/js/jquery.sparkline.min.js')}}"></script>
<!-- jvectormap -->
<script src="{{asset('backend/js/jquery-jvectormap-1.2.2.min.js')}}"></script>
<script src="{{asset('backend/js/jquery-jvectormap-world-mill-en.js') }}"></script>
<!-- jQuery Knob Chart -->
<script src="{{asset('backend/js/jquery.knob.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{asset('backend/js/moment.min.js') }}"></script>
<script src="{{asset('backend/js/daterangepicker.js') }}"></script>
<!-- datepicker -->
<script src="{{asset('backend/js/select2.full.min.js') }}"></script>
<script src="{{asset('backend/js/bootstrap-datepicker.min.js') }}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{asset('backend/js/bootstrap3-wysihtml5.all.min.js') }}"></script>

<script src="{{asset('backend/iCheck/icheck.min.js') }}"></script>
<!-- Slimscroll -->
<script src="{{asset('backend/js/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{asset('backend/js/fastclick.js') }}"></script>

<script src="{{asset('backend/js/jquery.dataTables.min.js') }}"></script>
<script src="{{asset('backend/js/dataTables.bootstrap.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{asset('backend/js/adminlte.min.js') }}"></script>

<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{asset('backend/js/dashboard.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('backend/js/demo.js') }}"></script>
<script src="{{asset('js/script.js') }}"></script>
<script src="{{asset('js/pusher.js') }}"></script>

<script src="https://js.pusher.com/5.0/pusher.min.js"></script>