routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth::routes();
Auth::routes(['verify' => true]);
Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');

Route::get('/readnotification/{id}', 'OrderController@readnotification')->name('readnotification');

    Route::get('/home', 'HomeController@index')->name('Home');

    Route::group(['middleware' => ['isAdmin', 'auth']], function() {

        Route::get('users/allUsers', 'UserController@index')->name('users.allusers');
        Route::resource('users', 'UserController');


        Route::get('roles/allRoles', 'RoleController@index')->name('roles.allroles');
        Route::resource('roles', 'RoleController');


        Route::get('permissions/allPermissions', 'PermissionController@index')->name('permissions.allpermissions');
        Route::resource('permissions', 'PermissionController');


        Route::get('keywords/allKeywords', 'KeywordController@index')->name('keywords.allkeywords');
        Route::resource('keywords', 'KeywordController');


        Route::get('industry/allIndustries', 'IndustryController@index')->name('industry.allindustries');
        Route::resource('industry', 'IndustryController');

    });

    Route::group(['prefix' => 'blogs', 'as' => 'blogs','middleware'=>'auth'],function (){

        Route::get('/','BlogController@index')->name('.index')->middleware('payment');

        Route::get('/allBlogs','BlogController@index')->name('.allblogs')->middleware('payment');
        Route::get('/list','BlogController@show')->name('.bloglist');
        Route::post('/searchresult', 'BlogController@blog_search')->name('.searchresult');
        Route::post('/store', 'BlogController@store')->name('.store');
        Route::get('/{id}/edit', 'BlogController@edit')->name('.edit');
        Route::get('/create','BlogController@create')->name('.create');
        Route::get('/{id}/delete', 'BlogController@destroy')->name('.destroy');
        Route::post('/{id}/update', 'BlogController@update')->name('.update');
        Route::post('/add_to_cart','BlogController@add_to_cart')->name('.add_to_cart');
        Route::post('/add_to_cart_update','BlogController@add_to_cart_update')->name('.add_to_cart_update');
        Route::get('/viewDetails/{id}', 'BlogController@viewDetails')->name('.viewDetails');
     });

   // Route::resource('blogs', 'BlogController')->middleware('isAdmin');
    // Route::get('/blogs', 'BlogController@index')->name('blogs.index')->middleware('auth','payment');
    // Route::get('/blogs/list', 'BlogController@show')->name('blogs.bloglist')->middleware('isAdmin');
    // Route::post('/blogs/searchresult','BlogController@blog_search')->name('blogs.searchresult')->middleware('auth');;
    // Route::post('/blogs/add_to_cart','BlogController@add_to_cart')->name('blogs.add_to_cart');
    // Route::post('/blogs/add_to_cart_update','BlogController@add_to_cart_update')->name('blogs.add_to_cart_update');


    Route::get('/cart','BlogController@cart')->name('blog.cart')->middleware('auth');
    Route::post('/cart_update','BlogController@cart_update')->name('blog.cart_update');
    Route::post('/cart_delete','BlogController@cart_delete')->name('blog.cart_delete');
    Route::get('/checkout','BlogController@checkout')->name('blog.checkout')->middleware('auth');

    Route::resource('orders', 'OrderController')->middleware('auth');
    //Route::post('/orders/update/{id}', 'OrderController@update')->name('orders.update');
    Route::get('paywithpaypal', array('as' => 'addmoney.paywithpaypal','uses' => 'AddMoneyController@payWithPaypal',));
    Route::post('paypal', array('as' => 'addmoney.paypal','uses' => 'AddMoneyController@postPaymentWithpaypal',));
    Route::get('paypal', array('as' => 'payment.status','uses' => 'AddMoneyController@getPaymentStatus',));
    Route::get('/orders/create', array('as' => 'orders.status','uses' => 'OrderController@getOrderStatus',));

resources/views/backend/cart.blade.php
@extends('layouts.backend.app')

@section('section')

    <style>
        .display {
            display: none;
        }
    </style>

    <div class="content-wrapper">

    @include('layouts.backend.alert')

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1> Cart </h1>
            <ol class="breadcrumb">
                <li><a href="{{route('Home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#" class="active">Cart</a></li>
            </ol>

        </section>


        <section class="content">

            <table id="cart" class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th style="width:35%">Blogs</th>
                    <th style="width:23%">Additional Details</th>
                    <th style="width:10%">Price</th>
                    {{-- <th style="width:8%">Quantity</th> --}}
                    <th style="width:20%" class="text-center">Subtotal</th>
                    <th style="width:12%">Action</th>
                </tr>
                </thead>
                <tbody>
                @if (empty($cart_data) == false)
            

                    @foreach($cart_data as $key => $data)
                    <?php $arr[] = $data['price']; ?>
                        <tr style="background:white;">

                            <td data-th="Product">
                                <div class="row">
                                    <div class="col-sm-3 hidden-xs">
                                    {{--      <img src="{{ asset('storage/'.$data['blog_image'] ) }}" alt="..."--}}
                                    {{--        class="img-responsive"/></div>--}}

                                    @if($data['blog_image'])
                                        <img src="{{asset('storage/'.$data['blog_image'])}}" alt="blogImage" class="blog-img-cart">
                                    @else
                                        <div>
                                            <img src="{{asset('images/no-image-available.png')}}" alt="placeHolder"
                                                 class="blog-img-cart">
                                        </div>
                                        {{--<div style="background-color: firebrick;height: 50vh;width: 100%;"></div>--}}
                                    @endif

                                    <div class="col-sm-9">
                                        <h4 class="nomargin">
                                            <a class="blog-href" style="color:black" href="{{route('blogs.viewDetails',$data['blog_id'])}}">{{ ucfirst($data['title']) }}</a>
                                        </h4>
                                    </div>
                                </div>
                            </td>
                            <td data-th="Price">DA: {{$data['da']}} <br> PA: {{$data['fb']}} <br> Organic
                                Traffic: {{$data['follower']}} - {{count($cart_data)}}</td>
                            <td data-th="Price">${{number_format($data['price'],0)}}</td>
                            {{-- <td data-th="Quantity">
                                <input type="number" class="form-control text-center" value="1">
                            </td> --}}
                            <td data-th="Subtotal" class="text-center"></td>
                            <td class="actions" data-th="">
                                {{-- <form method="post" enctype="multipart/form-data" action="{{route('blog.cart_update')}}">
                                    <input type="hidden" value="{{csrf_token()}}" name="_token"/>
                                    <input type="hidden" value="{{$data['title']}}" name="title"  /> --}}
                                {{-- <input type="hidden" value="{{current($data)}}" name="array_index"  /> --}}
                                {{-- <input type="hidden" value="{{$key}}" name="array_index"  />
                                <input type="hidden" value="{{$data['description']}}" name="description"/>
                                <input type="hidden" value="{{$data['price']}}" name="price"/>
                                <input type="hidden" value="{{$data['da']}}" name="da"/>
                                <input type="hidden" value="{{$data['fb']}}" name="fb"/>
                                <input type="hidden" value="{{$data['follower']}}" name="follower"/>
                                    <button class="btn btn-info btn-sm"><i class="fa fa-refresh"></i></button>
                                    </form> --}}
                                <form method="post" enctype="multipart/form-data"
                                      action="{{route('blog.cart_delete')}}">
                                    <input type="hidden" value="{{csrf_token()}}" name="_token"/>
                                    <input type="hidden" value="{{$data['title']}}" name="title"/>
                                    <input type="hidden" value="{{$key}}" name="array_index"/>
                                    <input type="hidden" value="{{$data['description']}}" name="description"/>
                                    <input type="hidden" value="{{$data['price']}}" name="price"/>
                                    <input type="hidden" value="{{$data['da']}}" name="da"/>
                                    <input type="hidden" value="{{$data['fb']}}" name="pa"/>
                                    <input type="hidden" value="{{$data['follower']}}" name="ahrefs organic traffic"/>
                                    <button class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></button>
                                </form>
                            </td>
                            {{-- </form> --}}
                        </tr>

                    @endforeach
                        <tr style="background:white;">
                            <td></td>
                            <td></td>
                            <td></td>
                            <td class="text-center"> <strong> {{ "$".number_format(array_sum($arr),0) }} </strong> </td>
                            <td></td>
                        </tr>
                @else
                    <th style="width:100%; text-align:center">
                        Cart Is Empty
                    </th>
                @endif
                </tbody>
                <tfoot>
                <tr class="visible-xs">
                    <td class="text-center"><strong></strong></td>
                </tr>
                <tr>
                    <td><a href="{{ route('blogs.index') }}" class="btn btn-warning"><i class="fa fa-angle-left"></i>
                            Continue Shopping</a></td>
                    <td colspan="2" class="hidden-xs"></td>
                    @if (empty($cart_data) == false)
                        <td class="hidden-xs text-center"><strong></strong></td>
                        <td><a href="{{ route('blog.checkout') }}" class="btn btn-warning"> Check Out <i
                                    class="fa fa-angle-right"></i></a></td>
                    @endif
                </tr>
                </tfoot>
            </table>


        </section>


        <!-- /.content -->
    </div>
@endsection

@section('script')
    <script>
        $(function () {
            $('#example1').DataTable()
            $('#example2').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
    </script>
@endsection

resources/views/backend/home.blade.php
@extends('layouts.backend.app')

@section('section')

    <?php

    use App\orders;
    use App\keyword;
    use App\Industry;
    use App\blog;


    $user       = Auth::user();
    $orders     = "";
    $keywords   = "";
    $industries = "";
    $blogs      = "";

    if($user->hasRole(1)){
        $orders = orders::latest()->get();
    }
    else{
        $current_user_id = Auth::user()->id;
        $orders = orders::where('user_id',$current_user_id)->latest()->get();
    }

    $blogs      = blog::all();
    $keywords   = keyword::all();
    $industries = Industry::all();


    ?>


    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Dashboard
                <small>Control panel</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{route('Home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Dashboard</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <!-- Small boxes (Stat box) -->
            <div class="row">
                @hasrole('admin')
                    <div class="col-lg-3 col-xs-6">
                        <!-- small box -->
                        <div class="small-box bg-aqua">
                            <div class="inner">
                                <h3>{{count($orders)}}</h3>

                                <p>Total Orders</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-bag"></i>
                            </div>
                            <a href="{{route('orders.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-3 col-xs-6">
                        <!-- small box -->
                        <div class="small-box bg-green">
                            <div class="inner">
                                <h3>{{count($keywords)}} <sup style="font-size: 20px"></sup></h3>

                                <p>Keywords</p>
                            </div>
                            <div class="icon">
                                <i class="fa fa-font"></i>
                            </div>
                            <a href="{{route('keywords.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-3 col-xs-6">
                        <!-- small box -->
                        <div class="small-box bg-yellow">
                            <div class="inner">
                                <h3>{{count($industries)}}</h3>

                                <p>Industries</p>
                            </div>
                            <div class="icon">
                                <i class="fa fa-industry"></i>
                            </div>
                            <a href="{{route('industry.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-3 col-xs-6">
                        <!-- small box -->
                        <div class="small-box bg-red">
                            <div class="inner">
                                <h3>{{count($blogs)}}</h3>

                                <p>Blogs</p>
                            </div>
                            <div class="icon">
                                <i class="fa fa-sticky-note-o"></i>
                            </div>
                            <a href="{{route('blogs.bloglist')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                @else
                    <div class="col-lg-3 col-xs-6">
                        <!-- small box -->
                        <div class="small-box bg-aqua">
                            <div class="inner">
                                <h3>{{count($orders)}}</h3>

                                <p>My Orders</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-bag"></i>
                            </div>
                            <a href="{{route('orders.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                @endrole
            </div>
            <!-- /.row -->


        </section>
        <!-- /.content -->
    </div>
@endsection