routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth::routes();
Auth::routes(['verify' => true]);
Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');

Route::get('/readnotification/{id}', 'OrderController@readnotification')->name('readnotification');

    Route::get('/home', 'HomeController@index')->name('Home');

    Route::group(['middleware' => ['isAdmin', 'auth']], function() {

        Route::get('users/allUsers', 'UserController@index')->name('users.allusers');
        Route::resource('users', 'UserController');


        Route::get('roles/allRoles', 'RoleController@index')->name('roles.allroles');
        Route::resource('roles', 'RoleController');


        Route::get('permissions/allPermissions', 'PermissionController@index')->name('permissions.allpermissions');
        Route::resource('permissions', 'PermissionController');


        Route::get('keywords/allKeywords', 'KeywordController@index')->name('keywords.allkeywords');
        Route::resource('keywords', 'KeywordController');


        Route::get('industry/allIndustries', 'IndustryController@index')->name('industry.allindustries');
        Route::resource('industry', 'IndustryController');

    });

    Route::group(['prefix' => 'blogs', 'as' => 'blogs','middleware'=>'auth'],function (){

        Route::get('/','BlogController@index')->name('.index')->middleware('payment');

        Route::get('/allBlogs','BlogController@index')->name('.allblogs')->middleware('payment');
        Route::get('/list','BlogController@show')->name('.bloglist');
        Route::post('/searchresult', 'BlogController@blog_search')->name('.searchresult');
        Route::post('/store', 'BlogController@store')->name('.store');
        Route::get('/{id}/edit', 'BlogController@edit')->name('.edit');
        Route::get('/create','BlogController@create')->name('.create');
        Route::get('/{id}/delete', 'BlogController@destroy')->name('.destroy');
        Route::post('/{id}/update', 'BlogController@update')->name('.update');
        Route::post('/add_to_cart','BlogController@add_to_cart')->name('.add_to_cart');
        Route::post('/add_to_cart_update','BlogController@add_to_cart_update')->name('.add_to_cart_update');
        Route::get('/viewDetails/{id}', 'BlogController@viewDetails')->name('.viewDetails');
     });

   // Route::resource('blogs', 'BlogController')->middleware('isAdmin');
    // Route::get('/blogs', 'BlogController@index')->name('blogs.index')->middleware('auth','payment');
    // Route::get('/blogs/list', 'BlogController@show')->name('blogs.bloglist')->middleware('isAdmin');
    // Route::post('/blogs/searchresult','BlogController@blog_search')->name('blogs.searchresult')->middleware('auth');;
    // Route::post('/blogs/add_to_cart','BlogController@add_to_cart')->name('blogs.add_to_cart');
    // Route::post('/blogs/add_to_cart_update','BlogController@add_to_cart_update')->name('blogs.add_to_cart_update');


    Route::get('/cart','BlogController@cart')->name('blog.cart')->middleware('auth');
    Route::post('/cart_update','BlogController@cart_update')->name('blog.cart_update');
    Route::post('/cart_delete','BlogController@cart_delete')->name('blog.cart_delete');
    Route::get('/checkout','BlogController@checkout')->name('blog.checkout')->middleware('auth');

    Route::resource('orders', 'OrderController')->middleware('auth');
    //Route::post('/orders/update/{id}', 'OrderController@update')->name('orders.update');
    Route::get('paywithpaypal', array('as' => 'addmoney.paywithpaypal','uses' => 'AddMoneyController@payWithPaypal',));
    Route::post('paypal', array('as' => 'addmoney.paypal','uses' => 'AddMoneyController@postPaymentWithpaypal',));
    Route::get('paypal', array('as' => 'payment.status','uses' => 'AddMoneyController@getPaymentStatus',));
    Route::get('/orders/create', array('as' => 'orders.status','uses' => 'OrderController@getOrderStatus',));

resources/views/backend/roles/add.blade.php
@extends('layouts.backend.app')

@section('section')
    <div class="content-wrapper">

    @include('layouts.backend.alert')

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Roles
                <small>Add Roles</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{route('Home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="{{route('roles.index')}}" class="active">Roles</a></li>
                <li class="active">Add Roles</li>
            </ol>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-md-12">

                    <div class="box box-primary">
                        <div class="box-header with-border">

                            <div class="col-md-6">
                                {{ Form::open(array('url' => 'roles')) }}

                                <div class="form-group">

{{--                                    <label class="col-form-label">Name</label>--}}
{{--                                    <input type="text" class="form-control @error('name') is-invalid @enderror"--}}
{{--                                           name="name" value="">--}}

                                    {{ Form::label('name', 'Name') }}
                                    {{ Form::text('name', null, array('class' => 'form-control @error("name") is-invalid @enderror')) }}

                                    @error('name')
                                    <span class="invalid-feedback" role="alert" style="color: red;">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror


                                </div>

                                <h5><b>Assign Permissions</b></h5>

                                <div class="form-group @error('permissions') is-invalid @enderror">
                                    @foreach ($permissions as $permission)
                                        {{ Form::checkbox('permissions[]',  $permission->id ) }}
                                        {{ Form::label($permission->name, ucfirst($permission->name)) }}<br>
                                    @endforeach

                                    @error('permissions')
                                    <span class="invalid-feedback" role="alert" style="color: red;">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror

                                </div>

                                {{ Form::submit('Add Role', array('class' => 'btn bg-navy')) }}

                                {{ Form::close() }}
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>


    {{--@endsection--}}
@endsection

@section('script')
    <script>
        $(function () {
            $('#example1').DataTable()
            $('#example2').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
    </script>
@endsection

resources/views/backend/roles/all.blade.php
@extends('layouts.backend.app')

@section('section')
    <div class="content-wrapper">

    @include('layouts.backend.alert')

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Roles
                <small>All Roles</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{route('Home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="{{route('roles.index')}}" class="active">Roles</a></li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>S.No</th>
                                    <th>Role</th>
                                    <th>Permissions</th>
                                    <th>Operation</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($roles as $key => $role)
                                <tr>
                                    <td>{{$key+1}}</td>
                                    <td>{{ $role->name }}</td>

                                    <td>{{ str_replace(array('[',']','"'),'', $role->permissions()->pluck('name')) }}</td>{{-- Retrieve array of permissions associated to a role and convert to string --}}
                                    <td>
                                        <a href="{{ URL::to('roles/'.$role->id.'/edit') }}" class="btn btn-primary pull-left" style="margin-right: 3px;"><i
                                                class="fa fa-pencil" aria-hidden="true"></i></a>

                                        {!! Form::open(['method' => 'DELETE', 'route' => ['roles.destroy', $role->id] ]) !!}

{{--                                        {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}--}}
                                        <button type="submit" class="btn btn-danger"> <i class="fa fa-trash"></i> </button>

                                        {!! Form::close() !!}

                                    </td>
                                </tr>
                                    @endforeach
                                </tbody>
{{--                                <tfoot>--}}
{{--                                <tr>--}}
{{--                                    <th>S.No</th>--}}
{{--                                    <th>Role</th>--}}
{{--                                    <th>Permissions</th>--}}
{{--                                    <th>Operation</th>--}}
{{--                                </tr>--}}
{{--                                </tfoot>--}}
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('script')
    <script>
        $(function () {
            $('#example1').DataTable()
            $('#example2').DataTable({
                'paging'      : true,
                'lengthChange': false,
                'searching'   : false,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : false
            })
        })
    </script>
@endsection

resources/views/backend/roles/edit.blade.php
@extends('layouts.backend.app')

@section('section')
    <div class="content-wrapper">

    @include('layouts.backend.alert')

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Roles
                <small>Edit Role</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{route('Home')}}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="{{route('roles.index')}}" class="active">Roles</a></li>
                <li class="active">Edit Role</li>
            </ol>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">

                            <div class="col-md-6">
                                {{ Form::model($role, array('route' => array('roles.update', $role->id), 'method' => 'PUT')) }}

                                <div class="form-group">
                                    {{ Form::label('name', 'Role Name') }}
                                    {{ Form::text('name', null, array('class' => 'form-control @error("name") is-invalid @enderror')) }}

                                    @error('name')
                                    <span class="invalid-feedback" role="alert" style="color: red;">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror

                                </div>

                                <h5><b>Assign Permissions</b></h5>
                                @foreach ($permissions as $permission)

                                    {{Form::checkbox('permissions[]',  $permission->id, $role->permissions ) }}
                                    {{Form::label($permission->name, ucfirst($permission->name)) }}<br>
                                @endforeach
                                @error('permissions')
                                    <span class="invalid-feedback" role="alert" style="color: red;">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                                <br>
                                {{ Form::submit('Update Role', array('class' => 'btn bg-navy')) }}

                                {{ Form::close() }}
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>


    {{--@endsection--}}
@endsection

@section('script')
    <script>
        $(function () {
            $('#example1').DataTable()
            $('#example2').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
    </script>
@endsection